### ISSUE TITLE
希望支持相对路径

### ISSUE THREAD

**Issue by svcvit** [GanymedeNil/srt2fcpxml#1]
使用相对路径有点问题，

➜  Desktop ./srt2fcpxml -srt CHS_测试.srt

提示：
open /CHS_测试.fcpxml: read-only file system
invalid argument

**Comment by GanymedeNil** [comment]
感谢提醒，今天晚些时候会修复

**Comment by GanymedeNil** [comment]
相对路径清这么使用
$./srt2fcpxml -srt ./CHS_测试.srt
