### ISSUE TITLE
srt中的双行字幕导出后不是双行了，在fcpxml中本该换行的地方是一个 - ，希望作者可以看一下哈。

### ISSUE THREAD

**Issue by nangonghan** [GanymedeNil/srt2fcpxml#10]
![image](https://user-images.githubusercontent.com/49426457/95804469-5414a900-0d35-11eb-861a-09d90d9f5f9e.png)
比如这里的srt字幕有的是双行的。
![image](https://user-images.githubusercontent.com/49426457/95804497-67277900-0d35-11eb-9362-26bd388f09e8.png)
然后转换到fcpxml中就是一个相连符。如果转换的过程中，能把srt的换行效果应用到fcpxml中就更好了

**Comment by GanymedeNil** [comment]
在 [v1.0.2](https://github.com/GanymedeNil/srt2fcpxml/releases/tag/v1.0.2) 版本中已修复此问题

**Comment by nangonghan** [comment]
干的漂亮
