### ISSUE TITLE
能否支持9:16的视频比例？

### ISSUE THREAD

**Issue by fqx** [GanymedeNil/srt2fcpxml#16]

**Comment by GanymedeNil** [comment]
可以在 core/fcpxml.go 中修改`SetWidth()` `SetHeight()` 参数后重新编译来满足你的需求

**Comment by fqx** [comment]
我重新编译了一下，但是有个问题，9:16的话要处理字幕换行。
https://github.com/fqx/srt2fcpxml/releases/tag/v2.0.0

**Comment by GanymedeNil** [comment]
> 我重新编译了一下，但是有个问题，9:16的话要处理字幕换行。 https://github.com/fqx/srt2fcpxml/releases/tag/v2.0.0

目前对于换行我也没有什么特别好的办法，因为本身fcp的文本不支持自动换行，需要手动去处理。我自己的解决方法是全选文本改字体大小，然后对于特别长的文本手动对其进行换行。

**Comment by fqx** [comment]
宽屏这个问题比较小，窄屏太常见了。
程序里面要是能加上一个最长字符数就好了，超过自动加换行。
当然有英文的话还要处理一下，不能把词中断。

**Comment by GanymedeNil** [comment]
> 
这个问题确实会比较麻烦还需要考虑各种语种字体的问题，我后续会想想有没有一劳永逸的办法。最新版本支持了输入分辨率参数 [v2.0.1](https://github.com/GanymedeNil/srt2fcpxml/releases/tag/v2.0.1)。这个issues我就关闭了，如果还有问题可以提新的issues。
