### ISSUE TITLE
read-only file system

### ISSUE THREAD

**Issue by small-tk** [GanymedeNil/srt2fcpxml#2]
macOS Catalina 由于SIP 不能写操作

### mac升级Catalina后系统出现read only file
macbook 升级了catalina系统后，在根目录下安装包或者是创建文件夹的时候，出现Read-only File system 的情况，按照一下操作步骤可以在根目录下进行改写。

1.禁止SIP
（1）点击左上角苹果样式的图标，找到关机，进行关机。
（2）点击开机键后直接按住command+R，直到进度条出现后再松开，一直等到完全开机。
（3）开机后就进入了Recovery模式，如果有选择字样则，选择简体中文，再点击➡️进入下一步。
（4）无论画面中出现什么都不要管，也不要点。在左上角点击实用工具，会出现下拉菜单，点击终端，打开终端输入：csrutil disable 回车即可。
（5）关闭终端，点击左上角苹果图标，选择关机。
（6）点击开机键，等待电脑重启。

2.输入命令
（1）重启后，在 terminal 输入 sudo mount -uw /
这个命令是把分区 mount 成可写模式。这个命令在系统重启后失效。

3 .删除或者修改文件
（1）进行自己的操作。

4 .启动SIP
（1）修改完文件后，可重启SIP，重复步骤1，但是在终端输入命令的时候
输入csrutil enable即可。

> 注意：启动SIP，下次在修改根目录文件时还是会出现Read-only File system的情况。

原文链接：https://blog.csdn.net/weixin_43624833/article/details/103035870

**Comment by tangino** [comment]
其实这个问题是软件本身的路劲没有处理好造成的，默认情况下，软件在srt所在的路劲生成转换后的文件，但是如果你使用软件时用的是相对路劲而不是绝对路径，那么转换文件就会生成在根目录下，而Catalina中，根目录是受保护的，造成只读错误。

**Comment by GanymedeNil** [comment]
已经解决
