### ISSUE TITLE
自动化

### ISSUE THREAD

**Issue by Jeson-f** [GanymedeNil/srt2fcpxml#5]
如果能实现这个功能，那就真的太棒了；
把字幕拖放进去，回车，然后终端询问转换多少帧的视频，输入参数，就可以直接在字幕原目录生成。
还有一个就是拖放文件夹，批量转换字幕。
如果这2个功能可以实现，都可以卖钱了

**Comment by GanymedeNil** [comment]
第一条很简单，正打算要这么做
第二条要实现也没太大难度，但是还是算了，因为主要针对个人用户
