### ISSUE TITLE
为什么我使用不是没有这个命令就是没有这个文件就是没权限...

### ISSUE THREAD

**Issue by sunjianan9900** [GanymedeNil/srt2fcpxml#6]
**1.使用绝对路径**
./Users/nan/Documents/srt2fcpxml -srt /Volumes/nan/NewF/download/200322-104220.srt
错误：./Users/nanDocuments/srt2fcpxml: No such file or directory
**2.在目录下使用相对路径**
./srt2fcpxml -srt /Volumes/nan/NewF/download/200322-104220.srt
./srt2fcpxml: Permission denied
**3.使用root**
sudo ./srt2fcpxml -srt /Volumes/nan/NewF/download/200322-104220.srt
sudo: ./srt2fcpxml: command not found

**Comment by GanymedeNil** [comment]
需要赋予程序执行权限 `chmod -x ./srt2fcpxml`

**Comment by sunjianan9900** [comment]
<img width="903" alt="WX20200322-230929@2x" src="https://user-images.githubusercontent.com/10936316/77252935-3812c280-6c92-11ea-8341-b3dcb717709a.png">
可是还是不行？我需要装go吗？

**Comment by GanymedeNil** [comment]
应该执行 `chmod +x ./srt2fcpxml` 我的问题

**Comment by sunjianan9900** [comment]
成功了～谢谢
