### ISSUE TITLE
期待支持更多帧率的fcpxml导出

### ISSUE THREAD

**Issue by Yang-Xijie** [GanymedeNil/srt2fcpxml#7]
如题，希望支持23.98p字幕的导出
感谢开发！
(其实我不太清楚24p和23.98p的区别，之前用23.98p创建的项目，导入24p的fcpxml有字幕重叠；刚刚重新试了一下调整项目的帧率为24p可以防止字幕重叠……）

**Comment by GanymedeNil** [comment]
目前应该不会出非整数帧率，因为fcp的非整数帧率计算比较复杂

**Comment by HyperSimon** [comment]
+1

**Comment by GanymedeNil** [comment]
#11
